### ISSUE TITLE
Unsupported Media Codec

### ISSUE THREAD

**Issue by mayank** [versatica/mediasoup-client#137]
Hi, 
  I am getting this error while the producer is producing the audio.

```
0|main  | [Nest] 5886   - 10/15/2020, 11:05:53 AM   [WsExceptionsHandler] unsupported codec [mimeType:audio/opus, payloadType:111] +201538ms
0|main  | UnsupportedError: unsupported codec [mimeType:audio/opus, payloadType:111]
0|main  |     at Object.getProducerRtpParametersMapping (/home/ubuntu/conference/node_modules/mediasoup/lib/ortc.js:503:19)
0|main  |     at WebRtcTransport.produce (/home/ubuntu/conference/node_modules/mediasoup/lib/Transport.js:242:33)
0|main  |     at MediaRoom.produce (/home/ubuntu/conference/src/xstream/mediasoup.ts:63:42)
0|main  |     at XstreamGateway.produce (/home/ubuntu/conference/src/xstream/xstream.gateway.ts:238:16)
0|main  |     at /home/ubuntu/conference/node_modules/@nestjs/websockets/context/ws-context-creator.js:43:33
0|main  |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is the code
```
    public async produce(userId, data) {
        console.log('About to Produce', userId, data.kind);

        const transport = this.clients[userId].media.producerTransport;
       // this line is causing the error
        const producer = await transport.produce({ ...data, appData: { userId, kind: data.kind } });
    }
```

**Comment by ibc** [comment]
Use the forum for usage questions of usage problems, please. Not a bug.

**Comment by mayank** [comment]
@ibc can we add a default issue template here that says this. It will save your time.

**Comment by ibc** [comment]
Yep, done now.
